[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5